openapi: 3.0.0
info:
  title: WxO L3 v2
  description: WxO L3 v2
  version: 0.1.0
servers:
  - url: https://wxo-l3-v2.1d13bpwyy9q7.us-east.codeengine.appdomain.cloud
paths:
  /query:
    get:
      tags:
        - Customers
      summary: Get a list of customers with recent life events
      description: Get a list of customers with recent life events
      operationId: customers_with_life_events
      parameters:
        - name: q
          in: query
          required: false
          schema:
            type: string
            default: q=select+Id,AccountId,Name,Email,Recent_Change__c,Child_Age__c,Child_Covered__c,Child_Name__c+from+contact+where+AccountId='001Hs00002ubq6YIAQ'
            title: Q
      responses:
        '200':
          description: Customers with recent life events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer_List'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /offers:
    post:
      summary: Search Offers
      description: Search for promotional offers.
      operationId: search_offers
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /credit:
    post:
      summary: Credit calculator
      description: Calculates a monthly payment schedule.
      operationId: credit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Customer:
      properties:
        name:
          type: string
          title: Name
        age:
          type: integer
          title: Age
          x-ibm-show: false
        id:
          type: string
          title: Id
          x-ibm-show: false
        email:
          type: string
          title: Email
        recent_change:
          type: string
          title: Recent Change
      type: object
      required:
        - name
        - age
        - id
        - email
        - recent_change
      title: Customer
    Customer_List:
      properties:
        totalSize:
          type: integer
          title: Totalsize
        records:
          items:
            $ref: '#/components/schemas/Customer'
          type: array
          title: Records
      type: object
      required:
        - totalSize
        - records
      title: Customer_List
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Message:
      properties:
        message:
          type: string
          title: Message
      type: object
      required:
        - message
      title: Message
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
    CreditRequest:
      properties:
        credit:
          type: number
          title: Credit
        rate:
          type: number
          title: Rate
      type: object
      required:
        - credit
        - rate
      title: CreditRequest
    CreditResponse:
      properties:
        monthly:
          type: number
          title: Monthly
        total:
          type: number
          title: Total
      type: object
      required:
        - monthly
        - total
      title: CreditResponse
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic
